export const services = [
  // MRI Analysis Services
  {
    id: "mri-class-static",
    title: "MRI Классификация (Static)",
    description: "Статическая классификация МРТ снимков",
    longDescription: "Deep Learning классификация МРТ изображений для диагностики нейродегенеративных заболеваний",
    iconName: "Scan",
    href: "/dashboard/mri-class-static",
    embedUrl: "https://class-stat.aman-ai.kz",
    team: ["Murat"],
    status: "active" as const,
  },
  {
    id: "mri-class-adaptive",
    title: "MRI Классификация (Adaptive)",
    description: "Адаптивная классификация МРТ снимков",
    longDescription: "Адаптивная Deep Learning классификация с обучением на новых данных",
    iconName: "Scan",
    href: "/dashboard/mri-class-adaptive",
    embedUrl: "https://class-adap.aman-ai.kz",
    team: ["Murat"],
    status: "active" as const,
  },
  {
    id: "mri-seg-static",
    title: "MRI Сегментация (Static)",
    description: "Статическая сегментация МРТ снимков",
    longDescription: "Сегментация областей мозга для выявления патологий",
    iconName: "Brain",
    href: "/dashboard/mri-seg-static",
    embedUrl: "https://seg-stat.aman-ai.kz",
    team: ["Murat"],
    status: "active" as const,
  },
  {
    id: "mri-seg-adaptive",
    title: "MRI Сегментация (Adaptive)",
    description: "Адаптивная сегментация МРТ снимков",
    longDescription: "Адаптивная сегментация с постоянным улучшением модели",
    iconName: "Brain",
    href: "/dashboard/mri-seg-adaptive",
    embedUrl: "https://seg-adap.aman-ai.kz",
    team: ["Murat"],
    status: "active" as const,
  },
  {
    id: "ml-static",
    title: "ML Анализ (Static)",
    description: "Статический ML анализ данных",
    longDescription: "Машинное обучение для анализа медицинских данных",
    iconName: "Cpu",
    href: "/dashboard/ml-static",
    embedUrl: "https://ml-stat.aman-ai.kz",
    team: ["Adilet"],
    status: "active" as const,
  },
  {
    id: "ml-adaptive",
    title: "ML Анализ (Adaptive)",
    description: "Адаптивный ML анализ данных",
    longDescription: "Адаптивное машинное обучение с автоматической донастройкой",
    iconName: "Cpu",
    href: "/dashboard/ml-adaptive",
    embedUrl: "https://ml-adap.aman-ai.kz",
    team: ["Adilet"],
    status: "active" as const,
  },
  // IoT & Questionnaire
  {
    id: "iot",
    title: "IoT Мониторинг",
    description: "Мониторинг показателей здоровья в реальном времени",
    longDescription: "PPG, IMU, EMG сенсоры для мониторинга стресса и состояния нервной системы",
    iconName: "Activity",
    href: "/dashboard/iot",
    embedUrl: null,
    team: ["Mukhammedzhan"],
    status: "active" as const,
  },
  {
    id: "questionnaire",
    title: "Опросники",
    description: "Интерактивные диагностические опросники",
    longDescription: "AI-анализ опросников для оценки уровня стресса и риска заболеваний",
    iconName: "ClipboardList",
    href: "/dashboard/questionnaire",
    embedUrl: null,
    team: ["Mukhammedzhan"],
    status: "active" as const,
  },
  {
    id: "cv-analysis",
    title: "CV Анализ",
    description: "Computer Vision анализ движений",
    longDescription: "Анализ движений и поз с помощью компьютерного зрения",
    iconName: "Eye",
    href: "/dashboard/cv-analysis",
    embedUrl: null,
    team: ["Mukhammedzhan"],
    status: "active" as const,
  },
  // Genetics & Blood
  {
    id: "genetics",
    title: "Генетический анализ",
    description: "Анализ генетических данных для диагностики",
    longDescription: "AlphaFold и ESMFold для анализа генетических данных и прогнозирования структуры белков",
    iconName: "Dna",
    href: "/dashboard/genetics",
    embedUrl: null,
    team: ["Samiullah", "Alnur"],
    status: "active" as const,
  },
  {
    id: "blood",
    title: "Анализ крови",
    description: "Интерпретация результатов анализа крови",
    longDescription: "ML-анализ показателей крови для выявления биомаркеров нейродегенеративных заболеваний",
    iconName: "Droplets",
    href: "/dashboard/blood",
    embedUrl: null,
    team: ["Samiullah", "Alnur"],
    status: "active" as const,
  },
  // Rehabilitation
  {
    id: "rehabilitation",
    title: "Реабилитация",
    description: "Персонализированные программы восстановления",
    longDescription: "YOLO и Computer Vision для отслеживания движений и персонализированной нейрореабилитации",
    iconName: "HeartPulse",
    href: "/dashboard/rehabilitation",
    embedUrl: null,
    team: ["Murat", "Adilet"],
    status: "active" as const,
  },
]

export type Service = typeof services[number]
export type ServiceStatus = "active" | "coming" | "maintenance"

